ALTER TABLE "User" DROP COLUMN "name";

ALTER TABLE "UserProfile"
ADD COLUMN "name" TEXT NOT NULL DEFAULT 'user123',
ALTER COLUMN "age"
DROP NOT NULL,
ALTER COLUMN "gender"
DROP NOT NULL,
ALTER COLUMN "height"
DROP NOT NULL,
ALTER COLUMN "weight"
DROP NOT NULL,
ALTER COLUMN "targetWeight"
DROP NOT NULL,
ALTER COLUMN "image"
SET NOT NULL,
ALTER COLUMN "image"
SET DEFAULT 'placeholder.png';